on: push
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
      - name: Add wasm32-wasip1 Rust target
        run: rustup target add wasm32-wasip1
      - name: Install rustfmt
        run: rustup component add rustfmt
        shell: bash
      - name: Check formatting
        run: cargo fmt --all -- --check
        shell: bash
      - name: Check source
        run: cargo check
        shell: bash
      - name: Install Compute local testing server
        run: cargo install viceroy
        shell: bash
      - name: Run tests
        run: cargo test
        shell: bash
